### ISSUE TITLE
响应错误

### ISSUE THREAD

**Issue by humorbeliever** [libli/chat#5]
{
  "error": {
    "message": "Invalid URL (GET /)",
    "type": "invalid_request_error",
    "param": null,
    "code": null
  }
}
日志输出success，响应显示这个

**Comment by libli** [comment]
这是哪里的响应？你部署个网页ChatGPT-Next-web看看

**Comment by humorbeliever** [comment]
{
  "cause": {
    "errno": -111,
    "code": "ECONNREFUSED",
    "syscall": "connect",
    "address": "127.0.0.1",
    "port": 8080
  }
}
我之前是在请求头里加token，然后响应之前那个。ChatGPT-Next-web网页是在哪里加token啊，我在这个apikey里加报这个错。

libo ***@***.***> 于2023年4月25日周二 13:20写道：
