### ISSUE TITLE
openai.error.ServiceUnavailableError: The server is overloaded or not ready yet.

### ISSUE THREAD

**Issue by Ikaros-521** [libli/chat#7]
![image](https://github.com/libli/chat/assets/40910637/32be31ff-8f1a-4281-bbe1-af180f0f0ca4)
![image](https://github.com/libli/chat/assets/40910637/9b373d1e-0e3c-41d7-a68b-3ecaafaf49b8)

**Comment by libli** [comment]
你用其它客户端能正常使用不？

**Comment by Ikaros-521** [comment]
> 你用其它客户端能正常使用不？

那倒是没试过www

**Comment by libli** [comment]
试下readme里面写的那些客户端，看你的后台能正常使用不。

**Comment by Ikaros-521** [comment]
# 1
 ![image](https://github.com/libli/chat/assets/40910637/74a5808e-cfdd-4985-b57b-494898c07bc2)
![image](https://github.com/libli/chat/assets/40910637/4e336634-e7af-4ea7-a69a-4928101ae7db)
这样配是用不了


# 2
按照文档部署（）
![image](https://github.com/libli/chat/assets/40910637/e0337b12-8ec8-4c77-9f18-f52fc250f9e3)
配置key为config的token同样报错

# 3
box配置时，没有看到填写token的地方
![image](https://github.com/libli/chat/assets/40910637/42cbd90a-5afa-4e0f-819a-ec9ad9aa5719)
![image](https://github.com/libli/chat/assets/40910637/827d11a1-6233-48aa-84f1-8faddc83f9d5)

**Comment by libli** [comment]
你需要把这个服务，部署在可以调用openai api的地区，如新加坡。然后通过公网IP的形式访问该api

**Comment by Ikaros-521** [comment]
> 你需要把这个服务，部署在可以调用openai api的地区，如新加坡。然后通过公网IP的形式访问该api

服务器在米国，同服务器有其他的代理程序可以正常使用

**Comment by libli** [comment]
没有这个问题。如果你还遇到问题可以邮件我私聊。

**Comment by Ikaros-521** [comment]
> 没有这个问题。如果你还遇到问题可以邮件我私聊。

难绷
